include: package:amplify_lints/dart.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - lib/model/transform_request.dart
    - lib/model/transform_response.dart

linter:
  rules:
    public_member_api_docs: ignore
