name: amplify_explorer
description: Amplify GraphQL transformer playground
version: 2.0.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  amplify_codegen:
    git:
      url: https://github.com/dnys1/amplify_codegen
      ref: main
  angular: ^7.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.2
  codemirror: ^0.6.0
  fo_components:
    path: third_party/fo_components
  grid_css: ^3.0.0
  http: ^0.13.4
  stream_transform: ^2.0.0
  uuid: ^3.0.5

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.1
  built_value_generator: ^8.1.2
  sass_builder: ^2.1.4
